language: java

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - wget https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.tar.gz
  - tar xvzf jdk-17_linux-x64_bin.tar.gz
  - rm -r jdk-17_linux-x64_bin.tar.gz
  - mv ./jdk-17.0.2 $HOME/jdk-17.0.2
  - export JAVA_HOME=$HOME/jdk-17.0.2
  - export PATH=$PATH:$JAVA_HOME/bin

script:
  - ./gradlew clean build

before_deploy:
  - zip -r travis-test ./build/libs/* ./appspec.yml ./travis.yml
  - mkdir -p deploy
  - mv travis-test.zip deploy/travis-test.zip

deploy:
  - provider: s3
    on:
      repo: oh980225/Travis_Practice
      branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: my-travis-test
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait_until_deployed: true

  - provider: codedeploy
    on:
      repo: oh980225/Travis_Practice
      branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: my-travis-test
    key: travis-test.zip
    bundle_type: zip
    application: travis-deploy
    deployment_group: travis-deploy-group
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - oh980225@gmail.com