language: java
jdk: openjdk10

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

script:
  - jdk_switcher use openjdk10
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
  - export JAVA_HOME=$HOME/jdk17
  - $TRAVIS_BUILD_DIR/install-jdk.sh -F 17 --target $JAVA_HOME
  - ./gradlew clean build

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - oh980225@gmail.com