language: java

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - wget https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.tar.gz
  - tar xvzf jdk-17_linux-x64_bin.tar.gz
  - export JAVA_HOME=$HOME/jdk-17_linux-x64_bin
  - java -version
  - chmod +x gradlew


# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - oh980225@gmail.com